### ISSUE TITLE
Bad support for user tools

### ISSUE THREAD

**Issue by crertel** [elierotenberg/react-armor#1]
Is there any chance that there could be a way of whitelisting or something similar for user tools?

This seems like the moral equivalent of right-click blocking and whatnot, something that doesn't really harm the bad guys but really inconveniences users.

It's also a little sad that this tool is helping to further lock down the open web. :(

I don't want to waste my own browser cycles to inconvenience my own plugins and extensions. :( :(

**Comment by elierotenberg** [comment]
I don't mean to, and I don't think this lib does, lock down the open web. It is a mean rather than an end. Developers that like the open web, like I do, will keep releasing open source and/or free software. This library simply enable developers to opt-out of having their application tampered with, which is only a side effect of how HTML and the DOM works rather than a core feature in my opinion.

**Comment by crertel** [comment]
Isn't it the user's choice to tamper with the application? For an example, if a user wishes to omit privacy-curtailing ads that would normally show up in an application, isn't that something we should support?

Also, on a less philosophical note: what does this do to things like screen readers?

**Comment by elierotenberg** [comment]
Privacy enforcement is usually performed by blocking network calls to tracking servers (via XHR, pixel trackers, or other related methods). This is out of the scope of this library, which only prevents third-party code (including but not restricted to browser extensions) from mutation the DOM nodes, aka the HTML/styles.

**Comment by elierotenberg** [comment]
Regarding screen readers, all the transforms are specifically designed to be able to left untouched certain parts of the DOM, most notably for accessibility and crawlability.

**Comment by crertel** [comment]
Thank you for your explanation, especially on the screen readers. :)

**Comment by elierotenberg** [comment]
You're most welcome :) Please feel free to reopen the issue if necessary.
