### ISSUE TITLE
Are there any use cases?

### ISSUE THREAD

**Issue by Amberlamps** [elierotenberg/react-armor#3]
Why would you need this module?
- If you have any third-party library messing with your markup, remove that library.
- If a user has some weird browser extension, there is not much you can do.
- If your app is vulnerable through third-party tampering other than any visual effects, obfucation is not going to help you. There are bigger problems.

**Comment by elierotenberg** [comment]
The typical use-cases are:
- Invasive/poorly coded ads typically coming from programmatic networks; even with a rather strict screening policy, programmatic networks occasionally deliver buggy ads which mess with your DOM
- Adblockers; this library is of course not the only answer to a complex problem to which a merely technical solution can not offer a complete response to, but it can help ad-supported free websites evade the arguably arbitrary nature of adblocking lists, especially regarding native, non-invasive ads.
